[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "1"

[[bin]]
name = "2"

[[bin]]
name = "3"

[[bin]]
name = "4"

[[bin]]
name = "5"

[[bin]]
name = "6"

[dependencies]
regex = "1.11.1"
